name: pytorch_inference
channels:
        - conda-forge
        - pytorch
dependencies:
        - jupyter
        - pytorch
        - torchvision
        - pip
        - numpy
        - protobuf
        - pip:
                - opencv-contrib-python
                - flask
                - flask_bootstrap
                - torchsummary
                - Pillow
                - onnx
                - matplotlib
                - future

